Covid/covid/HCS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('mainpage.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('blog/',include('blog.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Covid/covid/app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import datetime

# Create your models here.

class student(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	balance = models.IntegerField(default=0)
	phone = models.IntegerField(default=0)
	name = models.CharField(max_length=20,default='student')
	email = models.EmailField(max_length=100,default='@thapar.edu')
	Hostel = models.ForeignKey('Hostel',on_delete=models.DO_NOTHING,default=1)

class available_items(models.Model):
	Hostel = models.CharField(max_length=20)
	item_name = models.CharField(max_length=20)
	price = models.DecimalField(max_digits=4, decimal_places=2, default=0.00)
	hostel_num = models.IntegerField(default=1)
	quantity = models.IntegerField(default=10)
	def __str__(self):
		return self.item_name

class Hostel(models.Model):
	name = models.CharField(max_length=20)
	hostel_num = models.IntegerField(default=1)
	def __str__(self):
		return self.name

class ProperOrder(models.Model):
    order_client = models.ForeignKey(User, on_delete=models.CASCADE)
    order_timestamp = models.DateTimeField(auto_now_add=True)
    order_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, editable=False)
    order_done = models.BooleanField(default=False)
    hos = models.CharField(max_length=10,null=True)
    def __str__(self):
        return self.id

class Item(models.Model):
    in_order = models.ForeignKey(ProperOrder, on_delete=models.CASCADE, null=True, blank=True, related_name="item")
    already_ordered = models.BooleanField(default=False)
    add_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    itemtype = models.ForeignKey(available_items, on_delete=models.CASCADE,null=True)
    price = models.DecimalField(max_digits=4, decimal_places=2, default=0.00, editable=False)
    quantity = models.IntegerField(default=1)
    hostell = models.CharField(max_length=10,null=True)
    total = models.DecimalField(max_digits=4, decimal_places=0, default=0.00, editable=False)
    def calculate_price(self):
    	self.price = self.itemtype.price
    def __str__(self):
        return self.in_order

Covid/covid/app/templates/cart.html
{% extends 'homepage/base.html' %}
{% load static %}
{% block navitems %}
<ul class="navbar-nav ml-auto">	          
  <li class="nav-item"><a href="{% url 'account' %}" class="nav-link">My Account</a></li>
  <li><a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}" onclick="">Logout <strong>{{user.username}}</strong></a>
    <form class="" id="logout" action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <input type="hidden"  value="">
    </form></li>
</ul>
{% endblock navitems %}
{% block content %}
<style>
                    a { color: #FF0000; } /* CSS link color */
                th {
                background-color: #b10000;
                color: white;
                }
             </style>
<br>
<br>
    <section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
    				<div class="cart-list">
    					
	    					<table class="table">
	    						<style>
                th {
                background-color: #b10000;
                color: white;
                }
                </style>
						    	<thead class="thead-primary">
						      		<tr class="text-center">
						      			<th></th>
						      			<th>Sr. no.</th>
						      			<th>Hostel Name</th>
						                <th>Product name</th>
						                <th>Quantity</th>
								        <th>Price</th>
								        <th>Total</th>
						      		</tr>
						    	</thead>
						    <tbody>
						      <tr class="text-center">
{% with name="A" %}
						        {% if Item %}
				                    {% for item in Item %}
				                        <tr class="text-center mx-auto cardbody hovernow border border-danger" style="padding:3em;height:100px;margin:3em;">
				                        	<td class="product-remove"><a href="{% url 'remove_item' item.itemtype.id %}"><span class="ion-ios-close"></span></a></td>
				                        	<td scope="row">{{ forloop.counter }}</td>
				                        	<td>{{ item.itemtype.Hostel }}</td>
				                        	{% with name=item.itemtype.Hostel %}
			                            <td>{{ item.itemtype.item_name }}</td>
			                            <td>{{ item.quantity }}</td>
			                            <td>Rs. {{ item.price }}</td>
			                            <td>Rs. {{ item.total }}</td>
				                        </tr>
				                        {% endwith %}
				                    {% endfor %}
				                {% endif %}
						      </tr><!-- END TR-->
						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
    			<h4 style="text-align:center">Overall price:Rs. {{ price_all }}</h4>
            <div class="mt-2 col-md-12"></div>
            <div style="text-align: center;">
                <a href="{% url 'make_order'  %}"><input class="btn btn-danger btn-lg btn-block" type="button" value="Make order">
                </a>
            </div>
{% endwith %}
            <div class="mt-2 col-md-12"></div>
            <div style="text-align: center;">
                <a href="{% url 'clear_cart' %}"><input class="btn-outline-danger btn-sm" type="button" value="Delete order">
                </a>
            </div>
        </div>
		</section>
  </body>
  
  {% endblock content %}
</html>

Covid/covid/app/templates/index.html
{% extends 'homepage/base.html' %}

{% load static %}
{% block navitems %}
{% if user.is_authenticated and perms.app.change_available_items %}
<ul class="navbar-nav ml-auto">
<li class="nav-item active"><a href="{% url 'menu_today' user.username %}" class="nav-link">Today's Menu</a></li>
<li class="nav-item active"><a href="{% url 'totalsale' %}" class="nav-link">Total Sale</a></li>
<li><a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}" onclick="">Logout <strong>{{user.username}}</strong></a>
    <form class="" id="logout" action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <input type="hidden"  value="">
    </form></li>
</ul>
{% elif user.is_authenticated and perms.app.change_student %}
<ul class="navbar-nav ml-auto">
<li><a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}" onclick="">Logout <strong>{{user.username}}</strong></a>
    <form class="" id="logout" action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <input type="hidden"  value="">
    </form></li>
</ul>
{% else %}
<ul class="navbar-nav ml-auto">
<li class="nav-item"><a href="{% url 'account' %}" class="nav-link">My Account</a></li>
<li class="nav-item cta cta-colored"><a href="{% url 'cart' %}" class="nav-link"><span class="icon-shopping_cart"></span> Cart </a></li>
<li class="nav-item active"><a href="{% url 'user_orders_view' %}" class="nav-link">My orders</a></li>




<li><a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}" onclick="">Logout <strong>{{user.username}}</strong></a>
    <form class="" id="logout" action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <input type="hidden"  value="">
    </form></li>
</ul>
{% endif %}
{% endblock navitems %}
{% block content %}
  <body class="goto-here">
  {% if user.is_authenticated and perms.app.change_available_items %}

    <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center mb-3 pb-3">
          <div class="col-md-12 heading-section text-center ftco-animate">
            <br>
            <h2 class="mb-4">List Of Orders</h2>
            </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-12 ftco-animate">
            <div class="cart-list">
              <table class="table">
                <style>
                th {
                background-color: #94041c;
                color: white;
                }
                </style>
                <thead class="thead-primary">
                  <tr class="text-center">
                    <th scope="col" width="2%">Sr.</th>
                    <th scope="col" width="15%">Order Status</th>
                    <th scope="col" width="15%">Order Number</th>
                    <th scope="col" width="15%">Student Roll No.</th>
                    <th scope="col" width="20%">Timestamp</th>
                    <th scope="col" width="20%">Order Details</th>
                    <th scope="col" width="28%">Order Amount</th>
                  </tr>
                </thead>
                <tbody>
                {% if orders %}
                  {% for item in orders %}
                    <tr class="text-center mx-auto cardbody hovernow border border-danger" style="padding:3em;height:100px;margin:3em;">
                      <td scope="row">{{ forloop.counter }}</td>
                      <td>
                        {% if item.order_done == True %}
                          <i class="fa fa-check"></i>
                        {% else %}
                          </i><a href="/order/{{ item.id }}/done"><i class="fa fa-times"></i></a>
                        {% endif %}
                      </td>
                      <td>{{ item.id }}</td>
                      <td>{{ item.order_client }}</td>
                      <td>{{ item.order_timestamp  }} </td>
                      <td>
                        {% for ite in item.item.all %}
                          <li>{{ ite.itemtype.item_name }} ({{ite.quantity}})</li>
                          {% endfor %}
                      </td>
                      <td>Rs. {{ item.order_price }}</td>
                    </tr>
                  {% endfor %}
                {% endif %}
              </tbody>
          </table>
            </div>
          </div>
        </div>
          </div>
      </div>
    </section>

  {% elif user.is_authenticated and perms.app.change_student %}
    <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center mb-3 pb-3">
          <div class="col-md-12 heading-section text-center ftco-animate">
            <br>
            </section>
      <section>
        <div class="container">
        <div class="row justify-content-center mb-30 pb-30">
          <div class="col-md-12 heading-section text-center ftco-animate">
            <form class="form-center my-2" action="{% url 'search' %}" method="GET">

        <input

          class="form-control search-box"
          type="search"
          placeholder="Enter name of student"
          name="search_term"
          value="{{search_term}}"
        />
      </form></h6>
        </div>
      </div>
        <div class="row justify-content-center">
      <div class="col-xl-100">
            <div class="row mt-5 pt-3">
              <div class="col-md-12 d-flex mb-5">
                <div class="cart-detail cart-total p-3 p-md-4">
                </div>
              </div>
            </div>
      </div>
    </section>
  {% else %}
    <section class="ftco-section">
      
    	<div class="container">
				<div class="row justify-content-center mb-3 pb-3">
          <div class="col-md-12 heading-section text-center ftco-animate">
          	<br>
            <h1>Available Hostels:</h1>

        
            <div class="cart-list">
              <table class="table">
                <style>
                th{
                background-color: #94041c;
                color: white;
                }
                </style>
                <thead class="thead-primary">
                  <tr class="text-center">
                    <th scope="col" width="20%">Hostel No.</th>
                    <th scope="col" width="60%">Name</th>
                    <th scope="col" width="20%"></th>
                  </tr>
                </thead>
              <tbody>
                {% for hostel in Hostel %}
                  <tr class="text-center mx-auto cardbody hovernow border border-danger" style="padding:3em;height:100px;margin:3em;">
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{ hostel }}</td>
                    <td>
                      <style>
                      a { color: #94041c; } /* CSS link color */
                      </style>
                      <a href="{% url 'menu' hostel.hostel_num%}">View Menu</a></td>
                  </tr>
                {% endfor %}
              </tbody>
              </table>
             </div>
          </div>
        </div>
        </div>
        </div>
    </section>
{% endif %}

  </body>
  {% endblock content %}
</html>

Covid/covid/app/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static './css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static './css/animate.css' %}">
    
    <link rel="stylesheet" href="{% static './css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static './css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static './css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static './css/aos.css' %}">

    <link rel="stylesheet" href="{% static './css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static './css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static './css/jquery.timepicker.css' %}">

    
    <link rel="stylesheet" href="{% static './css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static './css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static './css/style.css' %}">
    <link rel="icon" type="image/png" href="{% static './images/icons/favicon.ico' %}"/>

	<link rel="stylesheet" type="text/css" href="{% static './fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static './fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static './css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static './css/main.css' %}">
  </head>
  <body class="goto-here">
		<div class="py-1 bg-primary">
    	<div class="container">
    		<div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
	    		<div class="col-lg-12 d-block">
		    		<div class="row d-flex">
		    			<div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
						    <span class="text">+91-7015757294</span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
						    <span class="text">mess.manage.thapar@gmail.com</span>
					    </div>
					    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
						    
					    </div>
				    </div>
			    </div>
		    </div>
		  </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="{% url 'user_login' %}">Welcome !</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item active"><a href="{% url 'mcms_home' %}" class="nav-link">Home</a></li>	          
		 
	          

	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->



    <section class="ftco-section">
    	<div class="container">
				<div class="row justify-content-center mb-3 pb-3">
          <div class="col-md-12 heading-section text-center ftco-animate">
          	<span class="subheading">Mess Canteen Management System Presents</span>
            
            
        </div>   		
        <h5>Account Login</h5>
    	</div>

        <div class="row justify-content-center">
						
			<div class="col-xl-100">
	          <div class="row mt-5 pt-3">
	          	<div class="col-md-12 d-flex mb-5">
	          		<div class="cart-detail cart-total p-3 p-md-4">
						<form method="post" action="{% url 'user_login' %}">
				        {% csrf_token %}
				        {# A more "HTML" way of creating the login form#}
				        
				       	<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>
					<div class="wrap-input100 validate-input" data-validate="Submit">
						<input type="submit" class="btn btn-success btn-lg btn-block"  name="" value="Login">
					</div>
				</form>
			</div>
	   	</div>
	   </section>
	
        
     
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Have a Question?</h2>
              <div class="block-23 mb-3">
                <ul>
                  <li><span class="icon icon-map-marker"></span><span class="text">Hostel M, Thapar Institute Of Engineering & Technology,Patiala</span></li>
<p></p>
                  <li><a href="#"><span class="icon icon-phone"></span><span class="text">+91-7015757294</span></a></li>
                  <li><a href="#"><span class="icon icon-envelope"></span><span class="text">ngoel_be17@thapar.edu</span></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p>
              Copyright &copy;<script>document.write(new Date().getFullYear());</script> | Made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href=# target="_blank">The Master Coders</a>
            </p>
          </div>
        </div>
      </div>
    </footer>
  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static './js/jquery.min.js' %}"></script>
  <script src="{% static './js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static './js/popper.min.js' %}"></script>
  <script src="{% static './js/bootstrap.min.js' %}"></script>
  <script src="{% static './js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static './js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static './js/jquery.stellar.min.js' %}"></script>
  <script src="{% static './js/owl.carousel.min.js' %}"></script>
  <script src="{% static './js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static './js/aos.js' %}"></script>
  <script src="{% static './js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static './js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static './js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static './js/google-map.js' %}"></script>
  <script src="{% static './js/main.js' %}"></script>

  <script>
    $(document).ready(function(){

    var quantitiy=0;
       $('.quantity-right-plus').click(function(e){
            
            // Stop acting like a button
            e.preventDefault();
            // Get the field name
            var quantity = parseInt($('#quantity').val());
            
            // If is not undefined
                
                $('#quantity').val(quantity + 1);

              
                // Increment
            
        });

         $('.quantity-left-minus').click(function(e){
            // Stop acting like a button
            e.preventDefault();
            // Get the field name
            var quantity = parseInt($('#quantity').val());
            
            // If is not undefined
          
                // Increment
                if(quantity>0){
                $('#quantity').val(quantity - 1);
                }
        });
        
    });
  </script>
    
  </body>
</html>

Covid/covid/app/templates/menu.html
{% extends 'homepage/base.html' %}
{% load static %}
{% block navitems %}
<ul class="navbar-nav ml-auto">
  <li class="nav-item"><a href="{% url 'account' %}" class="nav-link">My Account</a></li>
  <li class="nav-item cta cta-colored"><a href="{% url 'cart' %}" class="nav-link"><span class="icon-shopping_cart"></span> Cart </a></li>
  <li class="nav-item active"><a href="{% url 'user_orders_view' %}" class="nav-link">My orders</a></li>
  <li><a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}" onclick="">Logout <strong>{{user.username}}</strong></a>
    <form class="" id="logout" action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <input type="hidden"  value="">
    </form></li>
</ul>
{% endblock navitems %}
{% block content %}

    <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center mb-3 pb-3">
          <div class="col-md-12 heading-section text-center ftco-animate">
            <span class="subheading"><a href="#">Hostel Canteen Special</a></span>
            <h1>Aaj Ka Menu</h1>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert" style="text-align:center">
                <h6>{{ message }}</h6>
            </div>
        {% endfor %}
    {% endif %}
    <div class="cart-list">
              
              <table class="table">
                <style>
                a { color: #94041c; } /* CSS link color */
                th {
                background-color: #94041c;
                color: white;
                }
                </style>
                <thead class="thead-primary">
                  <tr class="text-center">

                  <th scope="col" width="2%">Sr.</th>
                  <th scope="col" width="33%">Name</th>
                  <th scope="col" width="25%">Quantity Available</th>
                  <th scope="col" width="15%">Price</th>
                  <th scope="col" width="25%">Add to cart</th>
        </tr>
        </thead>
        <tbody>
        {% for item_menu in menu %}
          
            <tr class="text-center mx-auto cardbody hovernow border border-danger" style="padding:3em;height:100px;margin:3em;">
                <td scope="row">{{ forloop.counter }}</td>
                <td>{{ item_menu.item_name }}</td>
                <td>{{ item_menu.quantity }}</td>
                <td>Rs. {{ item_menu.price }}</td>>
                <td><a href="/add/item/{{ item_menu.id }}/{{ item_menu.hostel_num }}"><span  class="icon-shopping_cart" color="#ff0000"></span></a></td>
                    
            </tr>
          
        {% endfor %}
        </tbody>
    </table>

    </section>

  </body>
  {% endblock content %}
</html>

Covid/covid/app/templates/menu_today.html
{% extends 'homepage/base.html' %}
{% load static %}
{% block navitems %}
<ul class="navbar-nav ml-auto">
  <li class="nav-item"><a href="{% url 'totalsale' %}" class="nav-link">Total Sale</a></li>
  <li><a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}" onclick="">Logout <strong>{{user.username}}</strong></a>
    <form class="" id="logout" action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <input type="hidden"  value="">
    </form></li>
</ul>
{% endblock navitems %}
{% block content %}
    <section class="ftco-section ftco-cart">
      <div class="container">
        <div class="row justify-content-center mb-3 pb-3">
          <div class="col-md-12 heading-section text-center ftco-animate">
            <span class="subheading"><a href="#">Hostel Buddies Presents</a></span>
            <h2 class="mb-4">Aaj ka Menu </h2>
            </div>
        </div>
      </div>
      {{All_items}}
      <div class="container">
        <div class="row">
          <div class="col-md-12 ftco-animate">
            <div class="cart-list">
              <table class="table">
                <style>

                a { color: #94041c; } /* CSS link color */
  
                th {
                background-color: #94041c;
                color: white;
                }
                </style>
                <thead class="thead-primary">
                  <tr class="text-center">
                    <th>Sr. No.</th>
                    <th>Product Id</th>
                    <th>Product name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                  </tr>
                </thead>
                <body>
                  {% for item_menu in menu %}
                      <tr class="text-center mx-auto cardbody hovernow border border-danger" style="padding:3em;height:100px;margin:3em;">
                        <td scope="row">{{ forloop.counter }}</td>
                        <td>{{ item_menu.id }}</td>
                        <td>{{ item_menu.item_name }}</td>

                        <td>Rs. {{ item_menu.price }}</td>>
                        <td class="quantity">

                      <form class="form-inline my-2" action="{% url 'mcms_update' item_menu.id %}" method="GET">
                      <input
                        class="form-control search-box"
                        type="update"
                        placeholder="{{ item_menu.quantity }}"
                        name="update_term"
                        value="{{update_term}}"
                      />

                    </form>
                    </td>
                      </tr>
                    {% endfor %}
                </tr><!-- END TR-->
               </tbody>
              </table>
            </div>
          </div>
        </div>
          </div>
      </div>
    </section>

  </body>
  {% endblock content %}
</html>

Covid/covid/app/templates/my_orders.html
{% extends 'homepage/base.html' %}
{% load static %}
{% block navitems %}
<ul class="navbar-nav ml-auto">
  <li class="nav-item"><a href="{% url 'account' %}" class="nav-link">My Account</a></li>
  <li class="nav-item cta cta-colored"><a href="{% url 'cart' %}" class="nav-link"><span class="icon-shopping_cart"></span> Cart </a></li>
  <li><a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}" onclick="">Logout <strong>{{user.username}}</strong></a>
    <form class="" id="logout" action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <input type="hidden"  value="">
    </form></li>
</ul>
{% endblock navitems %}
{% block content %}
    <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center mb-3 pb-3">
          <div class="col-md-12 heading-section text-center ftco-animate">
            <br>
            <h3>Your Order History : </h3>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert" style="text-align:center">
                <h6>{{ message }}</h6>
            </div>
        {% endfor %}
    {% endif %}
    <div class="cart-list">
              <table class="table">
                <style>
                    a { color: #94041c; } /* CSS link color */
                th {
                background-color: #94041c;
                color: white;
                }
                </style>
                <thead class="thead-primary">
                  <tr class="text-center">
            <th scope="col" width="2%">Sr.</th>
            <th scope="col" width="15%">Order Number</th>
            <th scope="col" width="23%">Timestamp</th>
            <th scope="col" width="15%">Hostel</th>
            <th scope="col" width="20%">Order Details</th>
            <th scope="col" width="15%">Order Amount</th>
            <th scope="col" width="10%">Order Status</th>

        </tr>
        </thead>
        <tbody>
        {% if orders %}
          {% for item in orders %}
            <tr class="text-center">
                <td scope="row">{{ forloop.counter }}</td>
                <td>{{ item.id }}</td>
                <td>{{ item.order_timestamp  }} </td>
                <td>{{ item.hos }}</td>
                <td>
                  {% for ite in item.item.all %}
                    <li>{{ ite.itemtype.item_name }} ({{ite.quantity}})</li>
                  {% endfor %}
                </td>

                <td>Rs. {{ item.order_price }}</td>
                <td>
                  {% if item.order_done == True %}
                    <i class="fa fa-check"></i>
                  {% else %}
                    <i class="fa fa-times"></i>
                  {% endif %}
                </td>
            </tr>
          {% endfor %}
        {% else %}
          <h2> You don't have ANY orders. It's time to change it!</h2>
        {% endif %}
        </tbody>
    </table>

    </section>



  </body>
  {% endblock content %}
</html>